version: '3.8'

services:
  # PostgreSQL データベース
  db:
    image: postgres:16-alpine
    container_name: learn-pm-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: learn_pm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Next.js アプリケーション
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: learn-pm-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/learn_pm
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npm run db:push && npm run dev"

volumes:
  postgres_data:
